// Code generated by protoc-gen-go-options. DO NOT EDIT.
// source: example.proto
package example

import (
	identifier "github.com/terwey/protoc-gen-go-options/example/identifier"
)

import (
	"google.golang.org/protobuf/proto"
)

// BasicMessageOption defines a functional option for BasicMessage.
type BasicMessageOption func(*BasicMessage)

// NewBasicMessage creates a new BasicMessage.
func NewBasicMessage(opts ...BasicMessageOption) *BasicMessage {
	m := &BasicMessage{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// ApplyBasicMessageOptions applies the provided options to an existing BasicMessage.
func ApplyBasicMessageOptions(m *BasicMessage, opts ...BasicMessageOption) *BasicMessage {
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithName sets the Name field.
func WithName(value string) BasicMessageOption {
	return func(m *BasicMessage) {
		m.Name = proto.String(value)
	}
}

// WithAge sets the Age field.
func WithAge(value int32) BasicMessageOption {
	return func(m *BasicMessage) {
		m.Age = proto.Int32(value)
	}
}

// WithIsActive sets the IsActive field.
func WithIsActive(value bool) BasicMessageOption {
	return func(m *BasicMessage) {
		m.IsActive = proto.Bool(value)
	}
}

// RepeatedFieldsMessageOption defines a functional option for RepeatedFieldsMessage.
type RepeatedFieldsMessageOption func(*RepeatedFieldsMessage)

// NewRepeatedFieldsMessage creates a new RepeatedFieldsMessage.
func NewRepeatedFieldsMessage(opts ...RepeatedFieldsMessageOption) *RepeatedFieldsMessage {
	m := &RepeatedFieldsMessage{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// ApplyRepeatedFieldsMessageOptions applies the provided options to an existing RepeatedFieldsMessage.
func ApplyRepeatedFieldsMessageOptions(m *RepeatedFieldsMessage, opts ...RepeatedFieldsMessageOption) *RepeatedFieldsMessage {
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithTags sets the Tags field.
func WithTags(values ...string) RepeatedFieldsMessageOption {
	return func(m *RepeatedFieldsMessage) {
		m.Tags = values
	}
}

// WithValues sets the Values field.
func WithValues(values ...int32) RepeatedFieldsMessageOption {
	return func(m *RepeatedFieldsMessage) {
		m.Values = values
	}
}

// NestedMessageOption defines a functional option for NestedMessage.
type NestedMessageOption func(*NestedMessage)

// NewNestedMessage creates a new NestedMessage.
func NewNestedMessage(opts ...NestedMessageOption) *NestedMessage {
	m := &NestedMessage{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// ApplyNestedMessageOptions applies the provided options to an existing NestedMessage.
func ApplyNestedMessageOptions(m *NestedMessage, opts ...NestedMessageOption) *NestedMessage {
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithNewBasicForNestedMessage sets the Basic field with a new instance.
func WithNewBasicForNestedMessage(opts ...BasicMessageOption) NestedMessageOption {
	return func(m *NestedMessage) {
		m.Basic = NewBasicMessage(opts...)
	}
}

// WithBasic sets the Basic field directly.
func WithBasic(value *BasicMessage) NestedMessageOption {
	return func(m *NestedMessage) {
		m.Basic = value
	}
}

// WithDescription sets the Description field.
func WithDescription(value string) NestedMessageOption {
	return func(m *NestedMessage) {
		m.Description = proto.String(value)
	}
}

// OneofMessageOption defines a functional option for OneofMessage.
type OneofMessageOption func(*OneofMessage)

// NewOneofMessage creates a new OneofMessage.
func NewOneofMessage(opts ...OneofMessageOption) *OneofMessage {
	m := &OneofMessage{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// ApplyOneofMessageOptions applies the provided options to an existing OneofMessage.
func ApplyOneofMessageOptions(m *OneofMessage, opts ...OneofMessageOption) *OneofMessage {
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithText sets the Choice oneof field to Text.
func WithText(value string) OneofMessageOption {
	return func(m *OneofMessage) {
		m.Choice = &OneofMessage_Text{
			Text: value,
		}
	}
}

// WithNumber sets the Choice oneof field to Number.
func WithNumber(value int32) OneofMessageOption {
	return func(m *OneofMessage) {
		m.Choice = &OneofMessage_Number{
			Number: value,
		}
	}
}

// ComplexMessageOption defines a functional option for ComplexMessage.
type ComplexMessageOption func(*ComplexMessage)

// NewComplexMessage creates a new ComplexMessage.
func NewComplexMessage(opts ...ComplexMessageOption) *ComplexMessage {
	m := &ComplexMessage{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// ApplyComplexMessageOptions applies the provided options to an existing ComplexMessage.
func ApplyComplexMessageOptions(m *ComplexMessage, opts ...ComplexMessageOption) *ComplexMessage {
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithNewNestedForComplexMessage sets the Nested field with a new instance.
func WithNewNestedForComplexMessage(opts ...NestedMessageOption) ComplexMessageOption {
	return func(m *ComplexMessage) {
		m.Nested = NewNestedMessage(opts...)
	}
}

// WithNested sets the Nested field directly.
func WithNested(value *NestedMessage) ComplexMessageOption {
	return func(m *ComplexMessage) {
		m.Nested = value
	}
}

// WithNestedList sets the NestedList field.
func WithNestedList(values ...*NestedMessage) ComplexMessageOption {
	return func(m *ComplexMessage) {
		m.NestedList = values
	}
}

// WithMetadata sets the Metadata field.
func WithMetadata(value map[string]int32) ComplexMessageOption {
	return func(m *ComplexMessage) {
		m.Metadata = value
	}
}

// FooOption defines a functional option for Foo.
type FooOption func(*Foo)

// NewFoo creates a new Foo.
func NewFoo(opts ...FooOption) *Foo {
	m := &Foo{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// ApplyFooOptions applies the provided options to an existing Foo.
func ApplyFooOptions(m *Foo, opts ...FooOption) *Foo {
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithNewIdForFoo sets the Id field with a new instance.
func WithNewIdForFoo() FooOption {
	return func(m *Foo) {
		m.Id = identifier.NewIdentifier()
	}
}

// WithIdForFoo sets the Id field directly.
func WithIdForFoo(value *identifier.Identifier) FooOption {
	return func(m *Foo) {
		m.Id = value
	}
}

// BarOption defines a functional option for Bar.
type BarOption func(*Bar)

// NewBar creates a new Bar.
func NewBar(opts ...BarOption) *Bar {
	m := &Bar{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// ApplyBarOptions applies the provided options to an existing Bar.
func ApplyBarOptions(m *Bar, opts ...BarOption) *Bar {
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithNewIdForBar sets the Id field with a new instance.
func WithNewIdForBar() BarOption {
	return func(m *Bar) {
		m.Id = identifier.NewIdentifier()
	}
}

// WithIdForBar sets the Id field directly.
func WithIdForBar(value *identifier.Identifier) BarOption {
	return func(m *Bar) {
		m.Id = value
	}
}

// SomeMessageOption defines a functional option for SomeMessage.
type SomeMessageOption func(*SomeMessage)

// NewSomeMessage creates a new SomeMessage.
func NewSomeMessage(opts ...SomeMessageOption) *SomeMessage {
	m := &SomeMessage{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// ApplySomeMessageOptions applies the provided options to an existing SomeMessage.
func ApplySomeMessageOptions(m *SomeMessage, opts ...SomeMessageOption) *SomeMessage {
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithNewIdentifierForSomeMessage sets the Identifier field with a new instance.
func WithNewIdentifierForSomeMessage() SomeMessageOption {
	return func(m *SomeMessage) {
		m.Identifier = identifier.NewIdentifier()
	}
}

// WithIdentifier sets the Identifier field directly.
func WithIdentifier(value *identifier.Identifier) SomeMessageOption {
	return func(m *SomeMessage) {
		m.Identifier = value
	}
}

// WithInclude sets the Include field.
func WithInclude(values ...*identifier.Identifier) SomeMessageOption {
	return func(m *SomeMessage) {
		m.Include = values
	}
}

// NoInitOption defines a functional option for NoInit.
type NoInitOption func(*NoInit)

// ApplyNoInitOptions applies the provided options to an existing NoInit.
func ApplyNoInitOptions(m *NoInit, opts ...NoInitOption) *NoInit {
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithNoInitName sets the NoInitName field.
func WithNoInitName(value string) NoInitOption {
	return func(m *NoInit) {
		m.NoInitName = proto.String(value)
	}
}

// FooBarWithEnumOption defines a functional option for FooBarWithEnum.
type FooBarWithEnumOption func(*FooBarWithEnum)

// NewFooBarWithEnum creates a new FooBarWithEnum.
func NewFooBarWithEnum(opts ...FooBarWithEnumOption) *FooBarWithEnum {
	m := &FooBarWithEnum{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// ApplyFooBarWithEnumOptions applies the provided options to an existing FooBarWithEnum.
func ApplyFooBarWithEnumOptions(m *FooBarWithEnum, opts ...FooBarWithEnumOption) *FooBarWithEnum {
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithStatus sets the Status field.
func WithStatus(value *FooBarWithEnum_Status) FooBarWithEnumOption {
	return func(m *FooBarWithEnum) {
		m.Status = value
	}
}
