// Code generated by protoc-gen-go-options. DO NOT EDIT.
// source: identifier.proto
package identifier

import (
	"google.golang.org/protobuf/proto"
)

// IdentifierOption defines a functional option for Identifier.
type IdentifierOption func(*Identifier)

// NewIdentifier creates a new Identifier.
func NewIdentifier(opts ...IdentifierOption) *Identifier {
	m := &Identifier{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// WithId sets the Id field.
func WithId(value string) IdentifierOption {
	return func(m *Identifier) {
		m.Id = proto.String(value)
	}
}
