// Code generated by protoc-gen-go-options. DO NOT EDIT.
// source: identifier.proto
// debug: log enabled
package identifier

import (
	"google.golang.org/protobuf/proto"
)

// debug: generating options for message: Identifier
// IdentifierOption defines a functional option for Identifier.
type IdentifierOption func(*Identifier)

// NewIdentifier creates a new Identifier.
// debug: qualifying identifier for name: Identifier
func NewIdentifier(opts ...IdentifierOption) *Identifier {
	m := &Identifier{}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// debug: generating field options for message: Identifier
// debug: generating scalar field option for message: Identifier
// debug: determining field type for field: Id
// debug: field kind: string
// WithId sets the Id field.
// debug: field is not a list
// debug: qualifying identifier for name: Identifier
func WithId(value string) IdentifierOption {
	return func(m *Identifier) {
		// debug: field is a scalar
		m.Id = proto.String(value)
	}
}

// debug: generating oneof options for message: Identifier
