name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache: true
	
      # Download and install the latest protoc
      - name: Install protoc
        run: |
          PROTOC_ZIP=protoc-29.2-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v29.2/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
          protoc --version # Verify installation

      # Install protoc and protoc-gen-go-options
      - name: Install dependencies
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install .

      # Run make generate
      - name: Generate code
        run: make generate

      # Run tests
      - name: Run tests
        uses: robherley/go-test-action@v0